
const SEED=window.MC_SEED, WEEK_MENU=window.MC_WEEK_MENU;
const DEFAULT_USERS=[{id:'u-admin',u:'admin',email:'admin@mak.local',p:'admin123',name:'Админ',role:'admin',enabled:true},{id:'u-nyarav',u:'nyarav',email:'nyarav@mak.local',p:'1234',name:'Нярав',role:'warehouse',enabled:true},{id:'u-togooch',u:'togooch',email:'togooch@mak.local',p:'1234',name:'Тогооч',role:'cook',enabled:true},{id:'u-manager',u:'manager',email:'manager@mak.local',p:'1234',name:'Удирдлага',role:'viewer',enabled:true}];
const ROLE={admin:'Админ',warehouse:'Нярав',cook:'Тогооч',viewer:'Удирдлага'};
const DAYS=['Даваа','Мягмар','Лхагва','Пүрэв','Баасан','Бямба','Ням'],MEALS=['breakfast','lunch','dinner','night'];
const MN={breakfast:'Өглөө',lunch:'Өдөр',dinner:'Орой',night:'Шөнө'};
const PID={breakfast:'peopleBreakfast',lunch:'peopleLunch',dinner:'peopleDinner',night:'peopleNight'};
const HID={breakfast:'menuBreakfast',lunch:'menuLunch',dinner:'menuDinner',night:'menuNight'};
const CAT_ORDER=['Мах, махан бүтээгдэхүүн','Ногоо','Будаа, үр тариа','Гурил, гоймон','Жимс','Лаазалсан бүтээгдэхүүн','Амтлагч, соус','Сүү, сүүн бүтээгдэхүүн, өндөг','Тос, өөх','Загас, далайн бүтээгдэхүүн','Ундаа, цай кофе','Хөлдөөсөн, бэлэн бүтээгдэхүүн','Аж ахуйн материал','Бусад'];
function catRank(c){let i=CAT_ORDER.indexOf(c);return i<0?999:i}
function displayCat(m){let c=String(m?.category||'').toLowerCase(),nm=String(m?.name||'').toLowerCase();
 if(/лааз|консерв|дарш|компот|томатны нухаш|эрдэнэ.?шиш/.test(nm))return 'Лаазалсан бүтээгдэхүүн';
 if(/үхэр|хонь|гахай|тахиа|булчин|сүүл|өвчүү|цул мах|мах|элэг|зүрх|хэл|гэдэс|ясны шөл|яс /.test(nm)||/мах/.test(c))return 'Мах, махан бүтээгдэхүүн';
 if(/загас|сам хорхой|кальмар|далайн/.test(nm)||/загас|далайн/.test(c))return 'Загас, далайн бүтээгдэхүүн';
 if(/төмс|лууван|сонгино|сарми|байцаа|редис|мөөг|өргөст хэмх|улаан лооль|помидор|чинжүү|манжин|хулуу|брокколи|цэцэгт байцаа|ногоон/.test(nm)||/ногоо/.test(c))return 'Ногоо';
 if(/алим|банан|жүрж|мандарин|лимон|усан үзэм|лийр|тарвас|амтат гуа|жимс/.test(nm)||/жимс/.test(c))return 'Жимс';
 if(/сүү|тараг|йогурт|аарц|бяслаг|цөцгий|зөөхий|өндөг/.test(nm)||/сүү|өндөг/.test(c))return 'Сүү, сүүн бүтээгдэхүүн, өндөг';
 if(/майонез|кетчуп|соус|жан|гич|давс|перец|чинжүүний нунтаг|цагаан гаа|карри|амтлагч|сахар|элсэн чихэр|уксус|цуу/.test(nm)||/амтлагч|соус/.test(c))return 'Амтлагч, соус';
 if(/тос|маргарин|масло|өөх/.test(nm)||/тос/.test(c))return 'Тос, өөх';
 if(/гурил|гоймон|макарон|талх|панко|крахмал|нунтаг төмс/.test(nm)||/талх|гурил/.test(c))return 'Гурил, гоймон';
 if(/будаа|овъёос|булгур|хөц|гурвалжин будаа|арвай|шар будаа/.test(nm)||/будаа|хуурай/.test(c))return 'Будаа, үр тариа';
 if(/ус$|ундаа|шүүс|цай|кофе|какао/.test(nm)||/ундаа|шүүс|цай|кофе/.test(c))return 'Ундаа, цай кофе';
 if(/хөлдөөсөн|бэлэн|фри|наггетс/.test(nm)||/хөлдөөсөн|бэлэн/.test(c))return 'Хөлдөөсөн, бэлэн бүтээгдэхүүн';
 if(/саван|бээлий|уут|салфетка|цэвэрлэгээ|угаалгын|ариутгал/.test(nm)||/аж ахуй/.test(c))return 'Аж ахуйн материал';
 return 'Бусад'}
function sortReqEntries(entries){return entries.sort((a,b)=>{let ma=mat(a[0]),mb=mat(b[0]),ca=displayCat(ma),cb=displayCat(mb),ra=catRank(ca),rb=catRank(cb);return ra-rb||String(ma?.name||a[1]?.name||'').localeCompare(String(mb?.name||b[1]?.name||''),'mn')})}
function groupTitle(c){return c||'Ангилалгүй'}
const $=id=>document.getElementById(id), n=v=>{v=Number(v);return Number.isFinite(v)?v:0}, fmt=v=>n(v).toLocaleString('mn-MN',{maximumFractionDigits:3});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10), now=()=>new Date().toISOString(), uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function load(k,f){try{let x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}} function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
let users=load('mc8_users',DEFAULT_USERS);
let user=null, mats=load('mc5_mats',SEED.materials.map(x=>({...x,balance:n(x.balance||x.opening||0),unit:x.stockUnit||x.unit}))), txns=load('mc5_txns',[]), plans=load('mc5_plans',{}), reqs=load('mc5_reqs',[]), activeReq=null, lastReport=null;
const cats=[...new Set(mats.map(displayCat))].sort((a,b)=>catRank(a)-catRank(b)||a.localeCompare(b,'mn')), dishCats=[...new Set(SEED.dishes.map(x=>x.dishCategory))].sort();
const mat=c=>mats.find(x=>String(x.code)===String(c)), dish=c=>SEED.dishes.find(x=>String(x.code)===String(c));
function message(t){$('msg').innerHTML='<div class="notice">'+esc(t)+'</div>';setTimeout(()=>$('msg').innerHTML='',3000)}
function canWrite(){if(user?.role==='viewer'){message('Энэ эрх зөвхөн харах зориулалттай.');return false}return true}
function login(){let key=$('loginUser').value.trim().toLowerCase(),pass=$('loginPass').value;let f=users.find(x=>x.enabled!==false&&(String(x.u||'').toLowerCase()===key||String(x.email||'').toLowerCase()===key)&&x.p===pass);if(!f){alert('Нэвтрэх мэдээлэл буруу эсвэл хэрэглэгч идэвхгүй байна');return}user=f;sessionStorage.setItem('mc5_user',JSON.stringify(f));showApp()}
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('who').textContent=user.name;$('role').textContent=ROLE[user.role];if($('settingsNav'))$('settingsNav').style.display=user.role==='admin'?'inline-block':'none';renderAll()}
function go(page){if(page==='settings'&&user?.role!=='admin'){message('Тохиргоо зөвхөн админд харагдана.');return}document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));$(page).classList.add('active');document.querySelector('.nav button[data-page="'+page+'"]')?.classList.add('active');if(page==='reports')runReport()}
function cycle(ds){let a=new Date('2026-09-09T00:00:00'),d=new Date(ds+'T00:00:00'),diff=Math.round((d-a)/86400000),idx=((2+diff)%14+14)%14;return{week:idx<7?1:2,day:DAYS[idx%7]}}
function scheduled(ds){let c=cycle(ds),src=WEEK_MENU[c.week][c.day],menu={breakfast:[],lunch:[],dinner:[],night:[]};for(let meal of MEALS)menu[meal]=(src[MN[meal]]||[]).map(x=>({...x,ratio:0}));for(let meal of MEALS){let base=inferPeople(menu[meal]);for(let x of menu[meal])x.ratio=base>0?Math.round(n(x.portions)/base*1000)/10:0}return{c,menu}}
function inferPeople(lines){let a=(lines||[]).filter(x=>n(x.portions)>0),mx=Math.max(0,...a.map(x=>n(x.portions)));let salad=a.filter(x=>/салат/i.test(x.type||''));let main=a.filter(x=>/үндсэн/i.test(x.type||''));let ss=salad.length>1?salad.reduce((s,x)=>s+n(x.portions),0):0,ms=main.length>1?main.reduce((s,x)=>s+n(x.portions),0):0;return Math.max(mx,ss,ms)}
function defaultPeople(menu){let p={};for(let meal of MEALS)p[meal]=inferPeople(menu[meal]);return p}
function dishCodeByName(name){let q=String(name||'').trim().toLowerCase(),d=SEED.dishes.find(x=>String(x.name||'').trim().toLowerCase()===q);return d?String(d.code):''}
function recipeQty(i){let q=n(i.net||i.gross),u=String(i.unit||'').toLowerCase();if(u==='г'||u==='гр')q/=1000;if(u==='мл')q/=1000;return q}
function calcReq(p){let r={};for(let meal of MEALS)for(let it of(p.menu[meal]||[])){let code=it.code||dishCodeByName(it.name);if(!code)continue;for(let ing of(SEED.recipes[code]||[])){let mc=String(ing.materialCode||'');if(!mc)continue;if(!r[mc])r[mc]={qty:0,name:ing.name};r[mc].qty+=recipeQty(ing)*n(it.portions)}}return r}
function addTxn(code,type,qty,note){let m=mat(code);if(!m||!qty)return;qty=Math.abs(n(qty));if(type==='IN'||type==='AUTO_RETURN')m.balance=n(m.balance)+qty;else if(type==='OUT'||type==='WASTE'||type==='AUTO_OUT')m.balance=n(m.balance)-qty;else if(type==='ADJUST')m.balance=n(m.balance)+n(qty);txns.unshift({id:uid(),created_at:now(),materialCode:m.code,materialName:m.name,type,qty,unit:m.unit,user:user?.name||'Систем',note:note||''})}
function renderAll(){renderHome();renderInventory();renderTxns();renderTech();renderRequests();renderSettings();loadPlan()}
function renderHome(){let low=mats.filter(x=>n(x.need14)>0&&n(x.balance)<n(x.need14));$('kMat').textContent=mats.length;$('kLow').textContent=low.length;let p=plans[today()],pp=0;if(p)for(let meal of MEALS)for(let x of(p.menu[meal]||[]))pp+=n(x.portions);$('kPortions').textContent=fmt(pp);$('kReq').textContent=reqs.filter(r=>r.status==='submitted').length}
function renderInventory(){let q=$('invSearch').value.toLowerCase(),c=$('invCat').value;let arr=mats.filter(x=>(!q||(x.name+' '+x.code).toLowerCase().includes(q))&&(!c||displayCat(x)===c)).sort((a,b)=>catRank(displayCat(a))-catRank(displayCat(b))||String(a.name).localeCompare(String(b.name),'mn'));$('invBody').innerHTML=arr.map((x,i)=>{let bal=n(x.balance),need=n(x.need14),st=bal<0?'<span class="badge bad">Хасах</span>':bal===0?'<span class="badge bad">Дууссан</span>':need>0&&bal<need?'<span class="badge warn">Бага</span>':'<span class="badge ok">Байгаа</span>';return '<tr><td class="rowno">'+(i+1)+'</td><td><b>'+esc(x.code)+'</b></td><td><b>'+esc(x.name)+'</b><div class="muted">'+esc(x.source||'')+'</div></td><td>'+esc(displayCat(x))+'</td><td>'+esc(x.unit)+'</td><td class="num"><b>'+fmt(bal)+'</b><br>'+st+'</td><td class="num">'+fmt(need)+'</td><td class="num">'+fmt(Math.max(0,need-bal))+'</td></tr>'}).join('')}
function renderTxns(){let q=$('txnSearch').value.toLowerCase();$('txnBody').innerHTML=txns.filter(t=>!q||(t.materialName+' '+t.type+' '+t.user).toLowerCase().includes(q)).slice(0,1000).map(t=>'<tr><td>'+esc(new Date(t.created_at).toLocaleString('mn-MN'))+'</td><td>'+esc(t.type)+'</td><td>'+esc(t.materialName)+'</td><td class="num">'+fmt(t.qty)+'</td><td>'+esc(t.unit)+'</td><td>'+esc(t.user)+'</td><td>'+esc(t.note)+'</td></tr>').join('')}
function renderTech(){let q=$('dishSearch').value.toLowerCase(),c=$('dishCat').value;$('dishList').innerHTML=SEED.dishes.filter(d=>(!q||(d.name+' '+d.code).toLowerCase().includes(q))&&(!c||d.dishCategory===c)).map(d=>'<div class="item"><div class="grow"><b>'+esc(d.name)+'</b><div class="muted">'+esc(d.dishCategory)+' · '+esc(d.code)+'</div></div><button class="btn small recipe" data-code="'+esc(d.code)+'">Орц</button></div>').join('')}
function addMenu(meal,x={name:'',type:'Нэмэлт',portions:0,ratio:0}){let div=document.createElement('div');div.className='menuline';let people=n($(PID[meal])?.value),ratio=n(x.ratio)||(people>0?n(x.portions)/people*100:0);div.dataset.ratio=ratio;div.innerHTML='<div class="dishwrap"><label class="mini">'+esc(x.type||'Хоол')+'</label><input class="dishName" list="dishNames" value="'+esc(x.name||dish(x.code)?.name||'')+'" placeholder="Хоолны нэр"></div><div><label class="mini">Хувь</label><div class="ratioView">'+fmt(ratio)+'%</div></div><div><label class="mini">Порц</label><input class="portion" type="number" step="any" value="'+fmt(n(x.portions))+'"></div><button class="btn small remove">×</button>';$(HID[meal]).appendChild(div)}
function syncRatiosFromPortions(meal){let people=n($(PID[meal]).value);for(let line of $(HID[meal]).querySelectorAll('.menuline')){let q=n(line.querySelector('.portion').value),r=people>0?q/people*100:0;line.dataset.ratio=r;let v=line.querySelector('.ratioView');if(v)v.textContent=fmt(r)+'%'}}
function scaleMeal(meal){let people=n($(PID[meal]).value);for(let line of $(HID[meal]).querySelectorAll('.menuline')){let r=n(line.dataset.ratio);line.querySelector('.portion').value=fmt(people*r/100)}updatePreview()}
function collectPlan(){let menu={breakfast:[],lunch:[],dinner:[],night:[]};for(let meal of MEALS){for(let line of $(HID[meal]).querySelectorAll('.menuline')){let name=line.querySelector('.dishName').value.trim(),ratio=n(line.dataset.ratio),portions=n(line.querySelector('.portion').value);if(name)menu[meal].push({name,code:dishCodeByName(name),type:line.querySelector('.mini').textContent,ratio,portions})}}return{date:$('planDate').value,people:Object.fromEntries(MEALS.map(m=>[m,n($(PID[m]).value)])),menu}}
function reqTable(rows,editable=false){if(!rows.length)return '<div class="muted">ТЭМ хэрэгцээ алга.</div>';let html='',last='',no=0;for(let x of rows){let c=x.category||'Ангилалгүй';if(c!==last){html+='<tr class="catrow"><td colspan="8">'+esc(groupTitle(c))+'</td></tr>';last=c}no++;html+='<tr><td class="rowno">'+no+'</td><td class="codecell"><b>'+esc(x.code)+'</b></td><td><b>'+esc(x.name)+'</b></td><td>'+esc(c)+'</td><td class="num">'+fmt(x.need)+'</td><td class="num">'+fmt(x.balance)+'</td><td class="num">'+(editable?'<input class="rqQty" data-code="'+esc(x.code)+'" type="number" step="any" min="0" value="'+fmt(x.qty)+'">':fmt(x.qty))+'</td><td>'+esc(x.unit)+'</td></tr>'}return '<div class="tablewrap reqtable"><table><thead><tr><th>№</th><th>MAK код</th><th>ТЭМ нэр</th><th>Ангилал</th><th class="num">Нийт хэрэгцээ</th><th class="num">Үлдэгдэл</th><th class="num">Шаардах</th><th>Нэгж</th></tr></thead><tbody>'+html+'</tbody></table></div>'}
function updatePreview(){let r=calcReq(collectPlan()),entries=sortReqEntries(Object.entries(r)),rows=entries.map(([c,x])=>{let m=mat(c),b=n(m?.balance),short=Math.max(0,x.qty-b);return{code:c,name:m?.name||x.name,category:displayCat(m),need:x.qty,balance:b,qty:short,unit:m?.unit||''}});$('planPreview').innerHTML=rows.length?reqTable(rows,false):'Технологийн карттай хоол сонгоогүй.'}
function loadPlan(){if(!$('planDate').value)$('planDate').value=today();let ds=$('planDate').value,a=scheduled(ds),p=plans[ds]||{date:ds,people:defaultPeople(a.menu),menu:a.menu,applied:{}};$('cycleLabel').innerHTML='<b>'+a.c.week+'-р долоо хоног · '+a.c.day+'</b> — Хүний тоог өөрчлөхөд порц автоматаар шинэчлэгдэнэ.';for(let meal of MEALS){let basePeople=n(p.people?.[meal])||inferPeople(p.menu?.[meal]||[])||n(defaultPeople(a.menu)[meal]);$(PID[meal]).value=basePeople;$(HID[meal]).innerHTML='';(p.menu?.[meal]||[]).forEach(x=>addMenu(meal,{...x,ratio:basePeople>0?n(x.portions)/basePeople*100:n(x.ratio)}))}updatePreview()}
function confirmPlan(){if(!canWrite())return;let p=collectPlan(),target=calcReq(p),old=plans[p.date]?.applied||{},codes=new Set([...Object.keys(target),...Object.keys(old)]);for(let c of codes){let d=n(target[c]?.qty)-n(old[c]);if(d>0)addTxn(c,'AUTO_OUT',d,'ТК автомат зарлага');else if(d<0)addTxn(c,'AUTO_RETURN',-d,'Цэс/порц буурсны буцаалт')}p.applied={};for(let[c,x]of Object.entries(target))p.applied[c]=x.qty;plans[p.date]=p;save('mc5_plans',plans);save('mc5_mats',mats);save('mc5_txns',txns);renderAll();message('Өдрийн олголт батлагдлаа.')}
function openReq(r){activeReq=r;$('reqTitle').textContent='ТЭМ шаардах хүсэлт · '+r.id;$('rqBranch').value=r.branch;$('rqWarehouse').value=r.warehouse;$('rqDate').value=r.needDate;$('rqNote').value=r.note||'';let adminEdit=user?.role==='admin',editable=r.status==='draft'||adminEdit;let rows=(r.lines||[]).map(x=>({code:x.code,name:x.name,category:displayCat(mat(x.code))||x.category,need:n(x.need||x.qty),balance:n(x.balance),qty:n(x.qty),unit:x.unit})).sort((a,b)=>catRank(a.category)-catRank(b.category)||String(a.name).localeCompare(String(b.name),'mn'));$('rqLines').innerHTML=reqTable(rows,editable);$('submitReqBtn').style.display=r.status==='draft'?'inline-block':'none';$('approveReqBtn').style.display=r.status==='submitted'&&['admin','warehouse'].includes(user.role)?'inline-block':'none';$('rejectReqBtn').style.display=r.status==='submitted'&&['admin','warehouse'].includes(user.role)?'inline-block':'none';$('fulfillReqBtn').style.display=r.status==='approved'&&['admin','warehouse'].includes(user.role)?'inline-block':'none';$('saveReqBtn').style.display=editable?'inline-block':'none';$('copyReqBtn').style.display='inline-block';$('downloadReqBtn').style.display='inline-block';$('reqModal').classList.add('open')}
function saveReqChanges(){if(!activeReq)return;if(activeReq.status!=='draft'&&user?.role!=='admin')return;for(let inp of $('rqLines').querySelectorAll('.rqQty')){let l=activeReq.lines.find(x=>String(x.code)===String(inp.dataset.code));if(l)l.qty=Math.max(0,n(inp.value))}activeReq.note=$('rqNote').value;activeReq.needDate=$('rqDate').value;activeReq.branch=$('rqBranch').value;activeReq.warehouse=$('rqWarehouse').value;activeReq.history=activeReq.history||[];activeReq.history.push({at:now(),by:user.name,status:activeReq.status,note:'Хүсэлт засварласан'});save('mc5_reqs',reqs);renderRequests();message('Хүсэлтийн өөрчлөлтийг хадгаллаа.')}
function saveDraftReqQty(){saveReqChanges()}
function copyReq(){if(!activeReq)return;if(activeReq.status==='draft'||user?.role==='admin')saveReqChanges();let lines=(activeReq.lines||[]).filter(x=>n(x.qty)>0).map(x=>({...x,category:displayCat(mat(x.code))||x.category})).sort((a,b)=>catRank(a.category)-catRank(b.category)||String(a.name).localeCompare(String(b.name),'mn'));let txt=['№\tАнгилал\tMAK код\tТЭМ нэр\tХэмжээ\tНэгж'];lines.forEach((x,i)=>txt.push([i+1,x.category,x.code,x.name,fmt(x.qty),x.unit].join('\t')));let done=()=>message('MAK ERP-д paste хийх хүсэлтийг хууллаа.');if(navigator.clipboard?.writeText)navigator.clipboard.writeText(txt.join('\n')).then(done).catch(()=>fallbackCopy(txt.join('\n')));else fallbackCopy(txt.join('\n'))}
function downloadReq(){if(!activeReq)return;if(activeReq.status==='draft'||user?.role==='admin')saveReqChanges();let lines=(activeReq.lines||[]).filter(x=>n(x.qty)>0).map(x=>({...x,category:displayCat(mat(x.code))||x.category})).sort((a,b)=>catRank(a.category)-catRank(b.category)||String(a.name).localeCompare(String(b.name),'mn'));let rows=[['№','Ангилал','MAK код','ТЭМ нэр','Хэмжээ','Нэгж']];lines.forEach((x,i)=>rows.push([i+1,x.category,x.code,x.name,x.qty,x.unit]));let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=(activeReq.id||'MAK_REQ')+'.csv';a.click();message('MAK ERP-д ашиглах CSV татагдлаа.')}
function fallbackCopy(t){let ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();message('MAK ERP-д оруулах хүсэлтийг хууллаа.')}
function newAutoReq(){if(!canWrite())return;let d=new Date();d.setDate(d.getDate()+1);let ds=d.toISOString().slice(0,10),a=scheduled(ds),p=plans[ds]||{date:ds,people:defaultPeople(a.menu),menu:a.menu},need=calcReq(p),lines=[];for(let[c,x]of sortReqEntries(Object.entries(need))){let m=mat(c),short=Math.max(0,x.qty-n(m?.balance));if(short>0)lines.push({code:c,name:m?.name||x.name,category:displayCat(m),need:x.qty,qty:short,unit:m?.unit||'',balance:n(m?.balance)})}let r={id:'REQ-'+new Date().toISOString().replace(/\D/g,'').slice(0,12),createdAt:now(),createdBy:user.name,branch:'Цемент - МАК Прайм Сервис',warehouse:'Хүнс',needDate:ds,note:'Маргаашийн цэс, ТК, үлдэгдлээс автоматаар тооцсон. Батлахаас өмнө хэмжээ засварлаж болно.',status:'draft',lines,history:[{at:now(),by:user.name,status:'draft'}]};reqs.unshift(r);save('mc5_reqs',reqs);renderRequests();openReq(r)}
function setReqStatus(st){if(!activeReq)return;activeReq.status=st;activeReq.history.push({at:now(),by:user.name,status:st});save('mc5_reqs',reqs);renderRequests();openReq(activeReq);message('Хүсэлтийн төлөв шинэчлэгдлээ.')}
function fulfillReq(){if(!activeReq)return;for(let x of activeReq.lines)addTxn(x.code,'IN',x.qty,'ТЭМ хүсэлт '+activeReq.id+' олгосон');activeReq.status='fulfilled';activeReq.history.push({at:now(),by:user.name,status:'fulfilled'});save('mc5_reqs',reqs);save('mc5_mats',mats);save('mc5_txns',txns);renderAll();openReq(activeReq)}
function statusLabel(s){return{draft:'Ноорог',submitted:'Хүлээгдэж буй',approved:'Батлагдсан',rejected:'Буцаасан',fulfilled:'Олгосон'}[s]||s}
function renderRequests(){let q=$('reqSearch').value.toLowerCase();$('requestList').innerHTML=reqs.filter(r=>!q||(r.id+' '+r.createdBy+' '+r.lines.map(x=>x.name+' '+x.code).join(' ')).toLowerCase().includes(q)).map(r=>'<button class="item reqOpen" data-id="'+esc(r.id)+'"><div class="grow" style="text-align:left"><b>'+esc(r.id)+'</b><div class="muted">'+esc(r.needDate)+' · '+esc(r.createdBy)+' · '+r.lines.length+' ТЭМ</div><div class="reqHint">Дарж доторх MAK код, хэмжээ, үлдэгдлийг харах</div></div><span class="badge '+(r.status==='approved'?'ok':r.status==='rejected'?'bad':r.status==='submitted'?'warn':'')+'">'+statusLabel(r.status)+'</span></button>').join('')||'<div class="muted">Хүсэлт алга.</div>'}
function renderSettings(){if(!$('userList'))return;if(user?.role!=='admin'){if($('settingsNav'))$('settingsNav').style.display='none';return}let active=users.filter(x=>x.enabled!==false).length;$('uTotal').textContent=users.length;$('uActive').textContent=active;$('uAdmin').textContent=users.filter(x=>x.role==='admin'&&x.enabled!==false).length;$('uReq').textContent=reqs.length;$('userList').innerHTML=users.map(x=>'<div class="item userRow"><div><b>'+esc(x.name)+'</b><div class="muted">@'+esc(x.u)+'</div></div><div class="email">'+esc(x.email||'И-мэйлгүй')+'</div><select class="userRole" data-id="'+esc(x.id||x.u)+'"><option value="admin" '+(x.role==='admin'?'selected':'')+'>Админ</option><option value="warehouse" '+(x.role==='warehouse'?'selected':'')+'>Нярав</option><option value="cook" '+(x.role==='cook'?'selected':'')+'>Тогооч</option><option value="viewer" '+(x.role==='viewer'?'selected':'')+'>Удирдлага</option></select><button class="btn small toggleUser" data-id="'+esc(x.id||x.u)+'">'+(x.enabled===false?'Идэвхжүүлэх':'Идэвхгүй болгох')+'</button><button class="btn small bad deleteUser" data-id="'+esc(x.id||x.u)+'" '+(x.u==='admin'?'disabled':'')+'>Хасах</button></div>').join('')}
function addUser(){if(user?.role!=='admin')return;let name=$('newUserName').value.trim(),email=$('newUserEmail').value.trim().toLowerCase(),u=$('newUserLogin').value.trim().toLowerCase(),p=$('newUserPass').value,role=$('newUserRole').value;if(!name||!email||!u||!p)return alert('Нэр, и-мэйл, нэвтрэх нэр, нууц үгийг бүгдийг оруулна уу.');if(users.some(x=>String(x.u).toLowerCase()===u||String(x.email||'').toLowerCase()===email))return alert('Ижил нэвтрэх нэр эсвэл и-мэйл бүртгэлтэй байна.');users.push({id:uid(),name,email,u,p,role,enabled:true});save('mc8_users',users);['newUserName','newUserEmail','newUserLogin','newUserPass'].forEach(id=>$(id).value='');renderSettings();message('Шинэ хэрэглэгч нэмэгдлээ.')}
function userAction(e){if(user?.role!=='admin')return;let el=e.target.closest('[data-id]');if(!el)return;let id=el.dataset.id,x=users.find(v=>(v.id||v.u)===id);if(!x)return;if(el.classList.contains('userRole')){if(x.u==='admin'&&el.value!=='admin'&&users.filter(v=>v.enabled!==false&&v.role==='admin').length<=1){el.value='admin';return alert('Сүүлийн админы эрхийг авч болохгүй.')}x.role=el.value;save('mc8_users',users);renderSettings();message('Хэрэглэгчийн эрх шинэчлэгдлээ.')}if(el.classList.contains('toggleUser')){if(x.u==='admin'&&x.enabled!==false&&users.filter(v=>v.enabled!==false&&v.role==='admin').length<=1)return alert('Сүүлийн админыг идэвхгүй болгож болохгүй.');x.enabled=x.enabled===false;save('mc8_users',users);renderSettings()}if(el.classList.contains('deleteUser')){if(x.u==='admin')return;if(confirm(x.name+' хэрэглэгчийг хасах уу?')){users=users.filter(v=>(v.id||v.u)!==id);save('mc8_users',users);renderSettings();message('Хэрэглэгч хасагдлаа.')}}}
function runReport(){let a=$('reportFrom').value,b=$('reportTo').value;if(!a||!b)return;let rt=txns.filter(t=>{let d=String(t.created_at).slice(0,10);return d>=a&&d<=b}),rp=Object.entries(plans).filter(([d])=>d>=a&&d<=b);let people=0,portions=0;for(let[,p]of rp)for(let meal of MEALS){people+=n(p.people?.[meal]);for(let x of(p.menu?.[meal]||[]))portions+=n(x.portions)}let auto=rt.filter(t=>t.type==='AUTO_OUT').reduce((s,t)=>s+n(t.qty),0),waste=rt.filter(t=>t.type==='WASTE').reduce((s,t)=>s+n(t.qty),0);$('rPeople').textContent=fmt(people);$('rPortions').textContent=fmt(portions);$('rAuto').textContent=fmt(auto);$('rWaste').textContent=fmt(waste);let by={};for(let t of rt.filter(t=>['AUTO_OUT','OUT','WASTE'].includes(t.type)))by[t.materialCode]=(by[t.materialCode]||0)+n(t.qty);$('rTop').innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).slice(0,20).map(([c,q])=>'<div class="item"><div class="grow"><b>'+esc(mat(c)?.name||c)+'</b><div class="muted">'+esc(mat(c)?.category||'')+'</div></div><div>'+fmt(q)+' '+esc(mat(c)?.unit||'')+'</div></div>').join('')||'Өгөгдөл алга.';let day={};for(let[d,p]of rp){let pc=0,pp=0;for(let meal of MEALS){pc+=n(p.people?.[meal]);for(let x of(p.menu?.[meal]||[]))pp+=n(x.portions)}day[d]={people:pc,portions:pp,auto:0,waste:0}}for(let t of rt){let d=String(t.created_at).slice(0,10);day[d]=day[d]||{people:0,portions:0,auto:0,waste:0};if(t.type==='AUTO_OUT')day[d].auto+=n(t.qty);if(t.type==='WASTE')day[d].waste+=n(t.qty)}$('rDaily').innerHTML='<div class="tablewrap"><table><thead><tr><th>Огноо</th><th class="num">Хүн</th><th class="num">Порц</th><th class="num">ТК зарлага</th><th class="num">Акт</th></tr></thead><tbody>'+Object.entries(day).sort().map(([d,x])=>'<tr><td>'+d+'</td><td class="num">'+fmt(x.people)+'</td><td class="num">'+fmt(x.portions)+'</td><td class="num">'+fmt(x.auto)+'</td><td class="num">'+fmt(x.waste)+'</td></tr>').join('')+'</tbody></table></div>';lastReport={a,b,people,portions,auto,waste,day}}
function preset(){let p=$('reportPreset').value,to=new Date(),from=new Date();if(p==='14')from.setDate(to.getDate()-13);else if(p==='month')from=new Date(to.getFullYear(),to.getMonth(),1);else return;$('reportFrom').value=from.toISOString().slice(0,10);$('reportTo').value=to.toISOString().slice(0,10)}
function exportReport(){if(!lastReport)runReport();if(!lastReport)return;let rows=[['Тайлан',lastReport.a+' - '+lastReport.b],['Нийт хүн',lastReport.people],['Нийт порц',lastReport.portions],['ТК зарлага',lastReport.auto],['Акт',lastReport.waste],[],['Огноо','Хүн','Порц','ТК зарлага','Акт']];for(let[d,x]of Object.entries(lastReport.day).sort())rows.push([d,x.people,x.portions,x.auto,x.waste]);let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='MC_report.csv';a.click()}
function showRecipe(code){let d=dish(code);$('recipeTitle').textContent=d?.name||'Технологи карт';$('recipeBody').innerHTML=(SEED.recipes[code]||[]).map(i=>'<div class="item"><div class="grow"><b>'+esc(i.name)+'</b><div class="muted">'+esc(i.materialCode)+'</div></div><div>'+fmt(recipeQty(i))+' '+esc(mat(i.materialCode)?.unit||i.unit)+'/порц</div></div>').join('')||'Орц олдсонгүй.';$('recipeModal').classList.add('open')}
function init(){
 let dl=document.createElement('datalist');dl.id='dishNames';dl.innerHTML=SEED.dishes.map(d=>'<option value="'+esc(d.name)+'"></option>').join('');document.body.appendChild(dl);
 $('invCat').innerHTML='<option value="">Бүх ангилал</option>'+cats.map(c=>'<option>'+esc(c)+'</option>').join('');$('dishCat').innerHTML='<option value="">Бүх хоол</option>'+dishCats.map(c=>'<option>'+esc(c)+'</option>').join('');$('tMat').innerHTML=mats.map(m=>'<option value="'+esc(m.code)+'">'+esc(m.name)+'</option>').join('');
 $('planDate').value=today();preset();
 $('loginBtn').onclick=login;$('logoutBtn').onclick=()=>{sessionStorage.removeItem('mc5_user');location.reload()};
 document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
 $('invSearch').oninput=renderInventory;$('invCat').onchange=renderInventory;$('txnSearch').oninput=renderTxns;$('dishSearch').oninput=renderTech;$('dishCat').onchange=renderTech;$('reqSearch').oninput=renderRequests;
 $('loadPlanBtn').onclick=loadPlan;$('planDate').onchange=loadPlan;$('confirmPlanBtn').onclick=confirmPlan;
 document.querySelectorAll('[data-addmeal]').forEach(b=>b.onclick=()=>{addMenu(b.dataset.addmeal);updatePreview()});
 for(let meal of MEALS){$(HID[meal]).addEventListener('input',e=>{if(e.target.classList.contains('portion'))syncRatiosFromPortions(meal);updatePreview()});$(HID[meal]).addEventListener('click',e=>{if(e.target.closest('.remove')){e.target.closest('.menuline').remove();updatePreview()}});$(PID[meal]).oninput=()=>scaleMeal(meal)}
 $('manualTxnBtn').onclick=()=>{if(canWrite())$('txnModal').classList.add('open')};$('saveTxnBtn').onclick=()=>{if(!canWrite())return;let q=n($('tQty').value);if(!q)return alert('Хэмжээ оруул');addTxn($('tMat').value,$('tType').value,q,$('tNote').value);save('mc5_mats',mats);save('mc5_txns',txns);$('txnModal').classList.remove('open');renderAll()};
 $('newAutoReqBtn').onclick=newAutoReq;$('requestList').onclick=e=>{let b=e.target.closest('.reqOpen');if(b)openReq(reqs.find(r=>r.id===b.dataset.id))};$('submitReqBtn').onclick=()=>{saveReqChanges();setReqStatus('submitted')};$('copyReqBtn').onclick=copyReq;$('downloadReqBtn').onclick=downloadReq;$('saveReqBtn').onclick=saveReqChanges;$('approveReqBtn').onclick=()=>{saveReqChanges();setReqStatus('approved')};$('rejectReqBtn').onclick=()=>setReqStatus('rejected');$('fulfillReqBtn').onclick=fulfillReq;
 $('reportPreset').onchange=preset;$('runReportBtn').onclick=runReport;$('exportReportBtn').onclick=exportReport;
 $('dishList').onclick=e=>{let b=e.target.closest('.recipe');if(b)showRecipe(b.dataset.code)};if($('addUserBtn'))$('addUserBtn').onclick=addUser;if($('userList')){$('userList').onclick=userAction;$('userList').onchange=userAction}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('open'));
 let ses=null;try{ses=JSON.parse(sessionStorage.getItem('mc5_user')||'null')}catch{}if(ses){let live=users.find(x=>(x.id&&x.id===ses.id)||x.u===ses.u);if(live&&live.enabled!==false){user=live;showApp()}else sessionStorage.removeItem('mc5_user')}
}
init();
