
const SEED=window.MC_SEED, WEEK_MENU=window.MC_WEEK_MENU;
const USERS=[{u:'admin',p:'admin123',name:'Админ',role:'admin'},{u:'nyarav',p:'1234',name:'Нярав',role:'warehouse'},{u:'togooch',p:'1234',name:'Тогооч',role:'cook'},{u:'manager',p:'1234',name:'Удирдлага',role:'viewer'}];
const ROLE={admin:'Админ',warehouse:'Нярав',cook:'Тогооч',viewer:'Удирдлага'};
const DAYS=['Даваа','Мягмар','Лхагва','Пүрэв','Баасан','Бямба','Ням'],MEALS=['breakfast','lunch','dinner','night'];
const MN={breakfast:'Өглөө',lunch:'Өдөр',dinner:'Орой',night:'Шөнө'};
const PID={breakfast:'peopleBreakfast',lunch:'peopleLunch',dinner:'peopleDinner',night:'peopleNight'};
const HID={breakfast:'menuBreakfast',lunch:'menuLunch',dinner:'menuDinner',night:'menuNight'};
const $=id=>document.getElementById(id), n=v=>{v=Number(v);return Number.isFinite(v)?v:0}, fmt=v=>n(v).toLocaleString('mn-MN',{maximumFractionDigits:3});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10), now=()=>new Date().toISOString(), uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function load(k,f){try{let x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}} function save(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}
let user=null, mats=load('mc5_mats',SEED.materials.map(x=>({...x,balance:n(x.balance||x.opening||0),unit:x.stockUnit||x.unit}))), txns=load('mc5_txns',[]), plans=load('mc5_plans',{}), reqs=load('mc5_reqs',[]), activeReq=null, lastReport=null;
const cats=[...new Set(mats.map(x=>x.category))].sort(), dishCats=[...new Set(SEED.dishes.map(x=>x.dishCategory))].sort();
const mat=c=>mats.find(x=>String(x.code)===String(c)), dish=c=>SEED.dishes.find(x=>String(x.code)===String(c));
function message(t){$('msg').innerHTML='<div class="notice">'+esc(t)+'</div>';setTimeout(()=>$('msg').innerHTML='',3000)}
function canWrite(){if(user?.role==='viewer'){message('Энэ эрх зөвхөн харах зориулалттай.');return false}return true}
function login(){let f=USERS.find(x=>x.u===$('loginUser').value.trim()&&x.p===$('loginPass').value);if(!f){alert('Нэвтрэх мэдээлэл буруу');return}user=f;sessionStorage.setItem('mc5_user',JSON.stringify(f));showApp()}
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('who').textContent=user.name;$('role').textContent=ROLE[user.role];renderAll()}
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));$(page).classList.add('active');document.querySelector('.nav button[data-page="'+page+'"]')?.classList.add('active');if(page==='reports')runReport()}
function cycle(ds){let a=new Date('2026-09-09T00:00:00'),d=new Date(ds+'T00:00:00'),diff=Math.round((d-a)/86400000),idx=((2+diff)%14+14)%14;return{week:idx<7?1:2,day:DAYS[idx%7]}}
function scheduled(ds){let c=cycle(ds),src=WEEK_MENU[c.week][c.day],menu={breakfast:[],lunch:[],dinner:[],night:[]};for(let meal of MEALS)menu[meal]=(src[MN[meal]]||[]).map(x=>({...x,ratio:0}));return{c,menu}}
function defaultPeople(menu){let p={};for(let meal of MEALS){let a=(menu[meal]||[]).map(x=>n(x.portions)).filter(x=>x>0);p[meal]=a.length?Math.max(...a):0}return p}
function dishCodeByName(name){let q=String(name||'').trim().toLowerCase(),d=SEED.dishes.find(x=>String(x.name||'').trim().toLowerCase()===q);return d?String(d.code):''}
function recipeQty(i){let q=n(i.net||i.gross),u=String(i.unit||'').toLowerCase();if(u==='г'||u==='гр')q/=1000;if(u==='мл')q/=1000;return q}
function calcReq(p){let r={};for(let meal of MEALS)for(let it of(p.menu[meal]||[])){let code=it.code||dishCodeByName(it.name);if(!code)continue;for(let ing of(SEED.recipes[code]||[])){let mc=String(ing.materialCode||'');if(!mc)continue;if(!r[mc])r[mc]={qty:0,name:ing.name};r[mc].qty+=recipeQty(ing)*n(it.portions)}}return r}
function addTxn(code,type,qty,note){let m=mat(code);if(!m||!qty)return;qty=Math.abs(n(qty));if(type==='IN'||type==='AUTO_RETURN')m.balance=n(m.balance)+qty;else if(type==='OUT'||type==='WASTE'||type==='AUTO_OUT')m.balance=n(m.balance)-qty;else if(type==='ADJUST')m.balance=n(m.balance)+n(qty);txns.unshift({id:uid(),created_at:now(),materialCode:m.code,materialName:m.name,type,qty,unit:m.unit,user:user?.name||'Систем',note:note||''})}
function renderAll(){renderHome();renderInventory();renderTxns();renderTech();renderRequests();loadPlan()}
function renderHome(){let low=mats.filter(x=>n(x.need14)>0&&n(x.balance)<n(x.need14));$('kMat').textContent=mats.length;$('kLow').textContent=low.length;let p=plans[today()],pp=0;if(p)for(let meal of MEALS)for(let x of(p.menu[meal]||[]))pp+=n(x.portions);$('kPortions').textContent=fmt(pp);$('kReq').textContent=reqs.filter(r=>r.status==='submitted').length}
function renderInventory(){let q=$('invSearch').value.toLowerCase(),c=$('invCat').value;let arr=mats.filter(x=>(!q||(x.name+' '+x.code).toLowerCase().includes(q))&&(!c||x.category===c));$('invBody').innerHTML=arr.map(x=>'<tr><td>'+esc(x.code)+'</td><td><b>'+esc(x.name)+'</b></td><td>'+esc(x.category)+'</td><td>'+esc(x.unit)+'</td><td class="num">'+fmt(x.balance)+'</td><td class="num">'+fmt(x.need14)+'</td><td class="num">'+fmt(Math.max(0,n(x.need14)-n(x.balance)))+'</td></tr>').join('')}
function renderTxns(){let q=$('txnSearch').value.toLowerCase();$('txnBody').innerHTML=txns.filter(t=>!q||(t.materialName+' '+t.type+' '+t.user).toLowerCase().includes(q)).slice(0,1000).map(t=>'<tr><td>'+esc(new Date(t.created_at).toLocaleString('mn-MN'))+'</td><td>'+esc(t.type)+'</td><td>'+esc(t.materialName)+'</td><td class="num">'+fmt(t.qty)+'</td><td>'+esc(t.unit)+'</td><td>'+esc(t.user)+'</td><td>'+esc(t.note)+'</td></tr>').join('')}
function renderTech(){let q=$('dishSearch').value.toLowerCase(),c=$('dishCat').value;$('dishList').innerHTML=SEED.dishes.filter(d=>(!q||(d.name+' '+d.code).toLowerCase().includes(q))&&(!c||d.dishCategory===c)).map(d=>'<div class="item"><div class="grow"><b>'+esc(d.name)+'</b><div class="muted">'+esc(d.dishCategory)+' · '+esc(d.code)+'</div></div><button class="btn small recipe" data-code="'+esc(d.code)+'">Орц</button></div>').join('')}
function addMenu(meal,x={name:'',type:'Нэмэлт',portions:0,ratio:0}){let div=document.createElement('div');div.className='menuline';div.innerHTML='<div class="dishwrap"><label class="mini">'+esc(x.type||'Хоол')+'</label><input class="dishName" list="dishNames" value="'+esc(x.name||dish(x.code)?.name||'')+'" placeholder="Нэрээр хай"></div><div><label class="mini">Хувь %</label><input class="ratio" type="number" value="'+n(x.ratio)+'"></div><div><label class="mini">Порц</label><input class="portion" type="number" value="'+n(x.portions)+'"></div><button class="btn small remove">×</button>';$(HID[meal]).appendChild(div)}
function collectPlan(){let menu={breakfast:[],lunch:[],dinner:[],night:[]};for(let meal of MEALS){for(let line of $(HID[meal]).querySelectorAll('.menuline')){let name=line.querySelector('.dishName').value.trim(),ratio=n(line.querySelector('.ratio').value),pv=line.querySelector('.portion').value,portions=pv===''?Math.round(n($(PID[meal]).value)*ratio/100):n(pv);if(name)menu[meal].push({name,code:dishCodeByName(name),type:line.querySelector('.mini').textContent,ratio,portions})}}return{date:$('planDate').value,people:Object.fromEntries(MEALS.map(m=>[m,n($(PID[m]).value)])),menu}}
function updatePreview(){let r=calcReq(collectPlan()),rows=Object.entries(r);$('planPreview').innerHTML=rows.length?'<div class="tablewrap"><table><thead><tr><th>ТЭМ</th><th>Ангилал</th><th class="num">Хэрэгцээ</th><th class="num">Үлдэгдэл</th><th>Төлөв</th></tr></thead><tbody>'+rows.map(([c,x])=>{let m=mat(c),b=n(m?.balance),ok=b>=x.qty;return'<tr><td>'+esc(x.name)+'</td><td>'+esc(m?.category||'')+'</td><td class="num">'+fmt(x.qty)+' '+esc(m?.unit||'')+'</td><td class="num">'+fmt(b)+'</td><td>'+(ok?'<span class="badge ok">Хүрэлцэнэ</span>':'<span class="badge bad">Дутуу '+fmt(x.qty-b)+'</span>')+'</td></tr>'}).join('')+'</tbody></table></div>':'Технологийн карттай хоол сонгоогүй.'}
function loadPlan(){if(!$('planDate').value)$('planDate').value=today();let ds=$('planDate').value,a=scheduled(ds),p=plans[ds]||{date:ds,people:defaultPeople(a.menu),menu:a.menu,applied:{}};$('cycleLabel').innerHTML='<b>'+a.c.week+'-р долоо хоног · '+a.c.day+'</b> — Excel цэс автоматаар';for(let meal of MEALS){$(PID[meal]).value=n(p.people?.[meal]);$(HID[meal]).innerHTML='';(p.menu?.[meal]||[]).forEach(x=>addMenu(meal,x))}updatePreview()}
function confirmPlan(){if(!canWrite())return;let p=collectPlan(),target=calcReq(p),old=plans[p.date]?.applied||{},codes=new Set([...Object.keys(target),...Object.keys(old)]);for(let c of codes){let d=n(target[c]?.qty)-n(old[c]);if(d>0)addTxn(c,'AUTO_OUT',d,'ТК автомат зарлага');else if(d<0)addTxn(c,'AUTO_RETURN',-d,'Цэс/порц буурсны буцаалт')}p.applied={};for(let[c,x]of Object.entries(target))p.applied[c]=x.qty;plans[p.date]=p;save('mc5_plans',plans);save('mc5_mats',mats);save('mc5_txns',txns);renderAll();message('Өдрийн олголт батлагдлаа.')}
function openReq(r){activeReq=r;$('reqTitle').textContent='ТЭМ шаардах хүсэлт · '+r.id;$('rqBranch').value=r.branch;$('rqWarehouse').value=r.warehouse;$('rqDate').value=r.needDate;$('rqNote').value=r.note||'';$('rqLines').innerHTML='<div class="tablewrap"><table><thead><tr><th>Бараа</th><th>Ангилал</th><th class="num">Хэмжээ</th><th>Нэгж</th><th class="num">Үлдэгдэл</th></tr></thead><tbody>'+r.lines.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.category)+'</td><td class="num">'+fmt(x.qty)+'</td><td>'+esc(x.unit)+'</td><td class="num">'+fmt(x.balance)+'</td></tr>').join('')+'</tbody></table></div>';$('submitReqBtn').style.display=r.status==='draft'?'inline-block':'none';$('approveReqBtn').style.display=r.status==='submitted'&&['admin','warehouse'].includes(user.role)?'inline-block':'none';$('rejectReqBtn').style.display=r.status==='submitted'&&['admin','warehouse'].includes(user.role)?'inline-block':'none';$('fulfillReqBtn').style.display=r.status==='approved'&&['admin','warehouse'].includes(user.role)?'inline-block':'none';$('reqModal').classList.add('open')}
function newAutoReq(){if(!canWrite())return;let d=new Date();d.setDate(d.getDate()+1);let ds=d.toISOString().slice(0,10),a=scheduled(ds),p=plans[ds]||{date:ds,people:defaultPeople(a.menu),menu:a.menu},need=calcReq(p),lines=[];for(let[c,x]of Object.entries(need)){let m=mat(c),short=Math.max(0,x.qty-n(m?.balance));if(short>0)lines.push({code:c,name:x.name,category:m?.category||'',qty:short,unit:m?.unit||'',balance:n(m?.balance)})}let r={id:'REQ-'+new Date().toISOString().replace(/\D/g,'').slice(0,12),createdAt:now(),createdBy:user.name,branch:'Цемент - МАК Прайм Сервис',warehouse:'Хүнс',needDate:ds,note:'Маргаашийн цэс, ТК, үлдэгдлээс автоматаар үүсгэсэн',status:'draft',lines,history:[{at:now(),by:user.name,status:'draft'}]};reqs.unshift(r);save('mc5_reqs',reqs);renderRequests();openReq(r)}
function setReqStatus(st){if(!activeReq)return;activeReq.status=st;activeReq.history.push({at:now(),by:user.name,status:st});save('mc5_reqs',reqs);renderRequests();openReq(activeReq);message('Хүсэлтийн төлөв шинэчлэгдлээ.')}
function fulfillReq(){if(!activeReq)return;for(let x of activeReq.lines)addTxn(x.code,'IN',x.qty,'ТЭМ хүсэлт '+activeReq.id+' олгосон');activeReq.status='fulfilled';activeReq.history.push({at:now(),by:user.name,status:'fulfilled'});save('mc5_reqs',reqs);save('mc5_mats',mats);save('mc5_txns',txns);renderAll();openReq(activeReq)}
function statusLabel(s){return{draft:'Ноорог',submitted:'Хүлээгдэж буй',approved:'Батлагдсан',rejected:'Буцаасан',fulfilled:'Олгосон'}[s]||s}
function renderRequests(){let q=$('reqSearch').value.toLowerCase();$('requestList').innerHTML=reqs.filter(r=>!q||(r.id+' '+r.createdBy+' '+r.lines.map(x=>x.name).join(' ')).toLowerCase().includes(q)).map(r=>'<button class="item reqOpen" data-id="'+esc(r.id)+'"><div class="grow" style="text-align:left"><b>'+esc(r.id)+'</b><div class="muted">'+esc(r.needDate)+' · '+esc(r.createdBy)+' · '+r.lines.length+' бараа</div></div><span class="badge '+(r.status==='approved'?'ok':r.status==='rejected'?'bad':r.status==='submitted'?'warn':'')+'">'+statusLabel(r.status)+'</span></button>').join('')||'<div class="muted">Хүсэлт алга.</div>'}
function runReport(){let a=$('reportFrom').value,b=$('reportTo').value;if(!a||!b)return;let rt=txns.filter(t=>{let d=String(t.created_at).slice(0,10);return d>=a&&d<=b}),rp=Object.entries(plans).filter(([d])=>d>=a&&d<=b);let people=0,portions=0;for(let[,p]of rp)for(let meal of MEALS){people+=n(p.people?.[meal]);for(let x of(p.menu?.[meal]||[]))portions+=n(x.portions)}let auto=rt.filter(t=>t.type==='AUTO_OUT').reduce((s,t)=>s+n(t.qty),0),waste=rt.filter(t=>t.type==='WASTE').reduce((s,t)=>s+n(t.qty),0);$('rPeople').textContent=fmt(people);$('rPortions').textContent=fmt(portions);$('rAuto').textContent=fmt(auto);$('rWaste').textContent=fmt(waste);let by={};for(let t of rt.filter(t=>['AUTO_OUT','OUT','WASTE'].includes(t.type)))by[t.materialCode]=(by[t.materialCode]||0)+n(t.qty);$('rTop').innerHTML=Object.entries(by).sort((a,b)=>b[1]-a[1]).slice(0,20).map(([c,q])=>'<div class="item"><div class="grow"><b>'+esc(mat(c)?.name||c)+'</b><div class="muted">'+esc(mat(c)?.category||'')+'</div></div><div>'+fmt(q)+' '+esc(mat(c)?.unit||'')+'</div></div>').join('')||'Өгөгдөл алга.';let day={};for(let[d,p]of rp){let pc=0,pp=0;for(let meal of MEALS){pc+=n(p.people?.[meal]);for(let x of(p.menu?.[meal]||[]))pp+=n(x.portions)}day[d]={people:pc,portions:pp,auto:0,waste:0}}for(let t of rt){let d=String(t.created_at).slice(0,10);day[d]=day[d]||{people:0,portions:0,auto:0,waste:0};if(t.type==='AUTO_OUT')day[d].auto+=n(t.qty);if(t.type==='WASTE')day[d].waste+=n(t.qty)}$('rDaily').innerHTML='<div class="tablewrap"><table><thead><tr><th>Огноо</th><th class="num">Хүн</th><th class="num">Порц</th><th class="num">ТК зарлага</th><th class="num">Акт</th></tr></thead><tbody>'+Object.entries(day).sort().map(([d,x])=>'<tr><td>'+d+'</td><td class="num">'+fmt(x.people)+'</td><td class="num">'+fmt(x.portions)+'</td><td class="num">'+fmt(x.auto)+'</td><td class="num">'+fmt(x.waste)+'</td></tr>').join('')+'</tbody></table></div>';lastReport={a,b,people,portions,auto,waste,day}}
function preset(){let p=$('reportPreset').value,to=new Date(),from=new Date();if(p==='14')from.setDate(to.getDate()-13);else if(p==='month')from=new Date(to.getFullYear(),to.getMonth(),1);else return;$('reportFrom').value=from.toISOString().slice(0,10);$('reportTo').value=to.toISOString().slice(0,10)}
function exportReport(){if(!lastReport)runReport();if(!lastReport)return;let rows=[['Тайлан',lastReport.a+' - '+lastReport.b],['Нийт хүн',lastReport.people],['Нийт порц',lastReport.portions],['ТК зарлага',lastReport.auto],['Акт',lastReport.waste],[],['Огноо','Хүн','Порц','ТК зарлага','Акт']];for(let[d,x]of Object.entries(lastReport.day).sort())rows.push([d,x.people,x.portions,x.auto,x.waste]);let csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='MC_report.csv';a.click()}
function showRecipe(code){let d=dish(code);$('recipeTitle').textContent=d?.name||'Технологи карт';$('recipeBody').innerHTML=(SEED.recipes[code]||[]).map(i=>'<div class="item"><div class="grow"><b>'+esc(i.name)+'</b><div class="muted">'+esc(i.materialCode)+'</div></div><div>'+fmt(recipeQty(i))+' '+esc(mat(i.materialCode)?.unit||i.unit)+'/порц</div></div>').join('')||'Орц олдсонгүй.';$('recipeModal').classList.add('open')}
function init(){
 let dl=document.createElement('datalist');dl.id='dishNames';dl.innerHTML=SEED.dishes.map(d=>'<option value="'+esc(d.name)+'"></option>').join('');document.body.appendChild(dl);
 $('invCat').innerHTML='<option value="">Бүх ангилал</option>'+cats.map(c=>'<option>'+esc(c)+'</option>').join('');$('dishCat').innerHTML='<option value="">Бүх хоол</option>'+dishCats.map(c=>'<option>'+esc(c)+'</option>').join('');$('tMat').innerHTML=mats.map(m=>'<option value="'+esc(m.code)+'">'+esc(m.name)+'</option>').join('');
 $('planDate').value=today();preset();
 $('loginBtn').onclick=login;$('logoutBtn').onclick=()=>{sessionStorage.removeItem('mc5_user');location.reload()};
 document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
 $('invSearch').oninput=renderInventory;$('invCat').onchange=renderInventory;$('txnSearch').oninput=renderTxns;$('dishSearch').oninput=renderTech;$('dishCat').onchange=renderTech;$('reqSearch').oninput=renderRequests;
 $('loadPlanBtn').onclick=loadPlan;$('planDate').onchange=loadPlan;$('confirmPlanBtn').onclick=confirmPlan;
 document.querySelectorAll('[data-addmeal]').forEach(b=>b.onclick=()=>{addMenu(b.dataset.addmeal);updatePreview()});
 for(let meal of MEALS){$(HID[meal]).addEventListener('input',updatePreview);$(HID[meal]).addEventListener('click',e=>{if(e.target.closest('.remove')){e.target.closest('.menuline').remove();updatePreview()}});$(PID[meal]).oninput=updatePreview}
 $('manualTxnBtn').onclick=()=>{if(canWrite())$('txnModal').classList.add('open')};$('saveTxnBtn').onclick=()=>{if(!canWrite())return;let q=n($('tQty').value);if(!q)return alert('Хэмжээ оруул');addTxn($('tMat').value,$('tType').value,q,$('tNote').value);save('mc5_mats',mats);save('mc5_txns',txns);$('txnModal').classList.remove('open');renderAll()};
 $('newAutoReqBtn').onclick=newAutoReq;$('requestList').onclick=e=>{let b=e.target.closest('.reqOpen');if(b)openReq(reqs.find(r=>r.id===b.dataset.id))};$('submitReqBtn').onclick=()=>setReqStatus('submitted');$('approveReqBtn').onclick=()=>setReqStatus('approved');$('rejectReqBtn').onclick=()=>setReqStatus('rejected');$('fulfillReqBtn').onclick=fulfillReq;
 $('reportPreset').onchange=preset;$('runReportBtn').onclick=runReport;$('exportReportBtn').onclick=exportReport;
 $('dishList').onclick=e=>{let b=e.target.closest('.recipe');if(b)showRecipe(b.dataset.code)};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.remove('open'));
 let ses=null;try{ses=JSON.parse(sessionStorage.getItem('mc5_user')||'null')}catch{}if(ses){user=ses;showApp()}
}
init();
